### ISSUE TITLE
php 8.1 issue

### ISSUE THREAD

**Issue by MrMooky** [bonecms/laravel-captcha#51]
I just updated my production server to php 8.1 and noticed, that the captcha is not working correctly anymore. For some reason it works locally, but takes about 5-8 seconds to load. Had no issue with php 8.0 before.

On my live server, I get the following exception and no image is being generated:

> production.ERROR: Call to undefined function Igoshev\Captcha\Captcha\Generator\ImageTTFtext() {"exception":"[object] (Error(code: 0): Call to undefined function Igoshev\\Captcha\\Captcha\\Generator\\ImageTTFtext() at /home/xxx/webapps/xxx/releases/20220128154920/vendor/bonecms/laravel-captcha/src/Captcha/Generator/GeneratorWaves.php:30)

<img width="1119" alt="Screenshot 2022-01-28 at 16 52 35" src="https://user-images.githubusercontent.com/3603346/151578969-fc2507bf-b6f4-450e-9a27-1c49d857fa91.png">

<img width="308" alt="Screenshot 2022-01-28 at 16 56 17" src="https://user-images.githubusercontent.com/3603346/151579201-01a7508c-b03c-41a1-a2b4-a029d7c9dd0a.png">

**Comment by tm1000** [comment]
You need to install php-gd.

**Comment by MrMooky** [comment]
I don't understand why this was closed. Like I said, it is working fine with PHP 8.0 but has issues with 8.1.

**Comment by tm1000** [comment]
@MrMooky its closed because it's looking for global functions but not finding them so it's falling back to the namespace

The global functions it's looking for are part of php-gd. You did not compile php gd with the right set of requirements or it's not installed. 

I'm using this with php 8.1 currently and it works fine 

See: https://www.php.net/manual/en/function.imagettftext.php

**Comment by some0ne2** [comment]
@MrMooky @tm1000 updated to php8.2, problem still persists.
@igoshev are you active here?
